# Generated by Django 5.2.5 on 2025-08-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_entre_mantenimiento', models.PositiveIntegerField(blank=True, help_text='Tiempo en días entre mantenimientos', null=True)),
            ],
        ),
    ]
