# Generated by Django 5.2.5 on 2025-08-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDeLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarios.listadeimpresion')),
            ],
        ),
    ]
