# Generated by Django 5.2.5 on 2025-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_itemdelista'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadeimpresion',
            name='tamano_etiqueta',
            field=models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=50),
        ),
    ]
