# Generated by Django 5.2.5 on 2025-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_listadeimpresion_tamano_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdelista',
            name='campo_adicional',
            field=models.CharField(blank=True, help_text='Campo adicional opcional para personalizar la etiqueta.', max_length=100, null=True),
        ),
    ]
