# Generated by Django 5.2.5 on 2025-08-21 21:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_rutina', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('frecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='core.frecuencia')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mantenimiento.rutina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('orden', models.PositiveIntegerField()),
                ('es_paso_critico', models.BooleanField(default=False, help_text='Marcar si este paso involucra un riesgo significativo de seguridad.')),
                ('peligro_asociado', models.TextField(blank=True, help_text='Descripción del peligro específico (ej: Contacto eléctrico, Exposición química).', null=True)),
                ('medida_de_control', models.TextField(blank=True, help_text='Equipo de protección personal requerido o acción para mitigar el peligro.', null=True)),
                ('nivel_riesgo_paso', models.CharField(blank=True, choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], max_length=5, null=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='mantenimiento.rutina')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PasosTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('orden', models.PositiveIntegerField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='mantenimiento.tarea')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
