# Generated by Django 5.2.5 on 2025-08-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_marca_activo_marca_modelo_activo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='tipo_de_activo',
            field=models.CharField(choices=[('ubicacion_funcional', 'Ubicación Funcional'), ('equipo', 'Equipo'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], default='otro', help_text='Tipo de activo (ej: Ubicación Funcional, Equipo, Herramienta, Otro).', max_length=50),
        ),
    ]
