# Generated by Django 5.2.5 on 2025-08-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_sistema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sistema',
        ),
    ]
