# Generated by Django 5.2.5 on 2025-08-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_modelo_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_plano', models.CharField(choices=[('proyecto_ejecutivo', 'Proyecto Ejecutivo'), ('asbuilt', 'Plano As Built')], max_length=50)),
                ('no_de_documento', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
