# Generated by Django 5.2.5 on 2025-08-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='nombre',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
