# Generated by Django 5.2.5 on 2025-08-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0012_activo_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipo_de_activo',
            field=models.CharField(choices=[('ubicacion_funcional', 'Ubicación Funcional'), ('equipo', 'Equipo'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], default='otro', help_text='Tipo de activo.', max_length=50),
        ),
    ]
