# Generated by Django 5.2.5 on 2025-08-21 21:55

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50, unique=True)),
                ('valor', models.IntegerField(help_text='Valor numérico (ej: 1 para Bajo, 5 para Alto)', unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='Probabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50, unique=True)),
                ('valor', models.IntegerField(help_text='Valor numérico (ej: 1 para Bajo, 5 para Alto)', unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gestion_riesgos.categoriariesgo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_identificacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_tratamiento', 'En Tratamiento'), ('cerrado', 'Cerrado'), ('mitigado', 'Mitigado')], default='abierto', max_length=20)),
                ('categoria', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_riesgos.categoriariesgo')),
                ('impacto', models.ForeignKey(help_text='Impacto o consecuencia si el riesgo ocurre.', on_delete=django.db.models.deletion.PROTECT, to='gestion_riesgos.impacto')),
                ('probabilidad', models.ForeignKey(help_text='Probabilidad de que el riesgo ocurra.', on_delete=django.db.models.deletion.PROTECT, to='gestion_riesgos.probabilidad')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos_propios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('riesgos_asociados', models.ManyToManyField(blank=True, related_name='peligros', to='gestion_riesgos.riesgo')),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Acción específica para mitigar, transferir, aceptar o evitar el riesgo.')),
                ('fecha_limite', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos_responsable', to=settings.AUTH_USER_MODEL)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='gestion_riesgos.riesgo')),
            ],
        ),
    ]
